import { Document } from './api';

export const mockDocuments: Document[] = [
  {
    id: '1',
    name: 'Regimento_Interno_2024.pdf',
    original_name: 'Regimento Interno 2024.pdf',
    type: 'application/pdf',
    size: 2458624,
    status: 'completed',
    upload_date: new Date(Date.now() - 86400000 * 2).toISOString(),
    text_length: 45320,
    chunks: 12,
    processing_time: 3500,
  },
  {
    id: '2',
    name: 'Manual_Procedimentos_Administrativos.docx',
    original_name: 'Manual de Procedimentos Administrativos.docx',
    type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    size: 1234567,
    status: 'completed',
    upload_date: new Date(Date.now() - 86400000 * 5).toISOString(),
    text_length: 28940,
    chunks: 8,
    processing_time: 2100,
  },
  {
    id: '3',
    name: 'Politica_Privacidade_LGPD.pdf',
    original_name: 'Política de Privacidade - LGPD.pdf',
    type: 'application/pdf',
    size: 987654,
    status: 'completed',
    upload_date: new Date(Date.now() - 86400000 * 7).toISOString(),
    text_length: 15670,
    chunks: 5,
    processing_time: 1800,
  },
  {
    id: '4',
    name: 'Guia_Estudante_2024.pdf',
    original_name: 'Guia do Estudante 2024.pdf',
    type: 'application/pdf',
    size: 3456789,
    status: 'processing',
    upload_date: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: '5',
    name: 'Calendario_Academico_2024.xlsx',
    original_name: 'Calendário Acadêmico 2024.xlsx',
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    size: 456123,
    status: 'completed',
    upload_date: new Date(Date.now() - 86400000 * 10).toISOString(),
    text_length: 8450,
    chunks: 3,
    processing_time: 900,
  },
];
